# Generated by Django 5.0.6 on 2024-09-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount_app', '0003_remove_user_username_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
